<?php

namespace Container1lCPl25;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestCommand' shared autowired service.
     *
     * @return \App\Command\TestCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/TestCommand.php';

        $container->privates['App\\Command\\TestCommand'] = $instance = new \App\Command\TestCommand();

        $instance->setName('app:test');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
