<?php

namespace ContainerXY6dkRe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateSoapClassesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GenerateSoapClassesCommand' shared autowired service.
     *
     * @return \App\Command\GenerateSoapClassesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GenerateSoapClassesCommand.php';

        $container->privates['App\\Command\\GenerateSoapClassesCommand'] = $instance = new \App\Command\GenerateSoapClassesCommand();

        $instance->setName('app:generate-soap-classes');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
