<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXY6dkRe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXY6dkRe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXY6dkRe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXY6dkRe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXY6dkRe\App_KernelDevDebugContainer([
    'container.build_hash' => 'XY6dkRe',
    'container.build_id' => '5547ca37',
    'container.build_time' => 1643968594,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXY6dkRe');
